### ISSUE TITLE
Design request

### ISSUE THREAD

**Issue by ingo916** [QuinnDamerell/OctoPrint-OctoEverywhere#11]
Would it be possible to do the following for users after they creat an account
1. Move the octoeverywhere to the bottom of the screen?
2. Remove setup now, powerful,secure, and simple(not really needed since users created an account)
3. From a mobile device like an iPad the connect buttons open the link in the same window. Could you make it so that the connect button opens the printer in a new tab? Would make it easier to go back to the dashboard to manage other printers. 
4. When viewing the control tab in octoprint viewing a web cam it will stop streaming after a short time. Can you auto refresh the page to update the data from octoprint?
![8DCF61ED-1C0F-4D48-BB49-295E8CE7040C](https://user-images.githubusercontent.com/41309095/102004782-9ff9b500-3cc8-11eb-98cd-53f2086a0a0b.jpeg)

**Comment by QuinnDamerell** [comment]
Thanks for those suggestions! for 1 & 2 that's something I will put on my backlog to consider. 

#3 is interesting, I haven't really thought of that, let me see what I can do. :)

#4 is by design. The entire website will stay connected, but right now OctoEverywhere limits webcam streams to 20 seconds for free accounts and 2 minutes for support accounts. So everything about the site still works, but when the webcam gets cut off it will just freeze on the last image. I'm working on a better UI for that, so it's more clear to users why the camera stopped.
