### ISSUE TITLE
OctoEverywhere - Multi Printer Support!

### ISSUE THREAD

**Issue by QuinnDamerell** [QuinnDamerell/OctoPrint-OctoEverywhere#37]
Big news... with version 2.4.0, our plug-in now supports remote access for multiple Klipper/Moonraker instances running on the same device!

We are on a final push toward our big launch, so pound on the plug-in hard and be sure to let us know if you have any issues or feedback! 🚀

**Comment by pauluchin** [comment]
Thanks 4 the good job and support for klipper

**Comment by Higachikunideguchi** [comment]
After that update i cant connect to mainsail localy, even reinstall all linux not help... wtf>

**Comment by QuinnDamerell** [comment]
@Higachikunideguchi - thanks for letting me know! Are you able to ssh into the device?

**Comment by Higachikunideguchi** [comment]
I repaired it on Saturday - i dont know why and when, but something close
porta for communication. I use Linux Mint on terminalPC instead of
RaspberryPi, do its little harder to solve. Propably the problem was on
system - after installing New system same problem, fixed manualny.

niedz., 19 mar 2023, 04:44 użytkownik Quinn Damerell <
***@***.***> napisał:
