### ISSUE TITLE
Gadget based lighting in klipper

### ISSUE THREAD

**Issue by spitfire1337** [QuinnDamerell/OctoPrint-OctoEverywhere#39]
I'm in the process of finishing up my latest printer build and am adding addressable LEDs to the chamber lighting when I had an idea that would be pretty cool if it could be implemented into the octoeverywhere plugin.

Basically my thought is if gadget detects something it could trigger a lighting color change that's specified, for instance to orange on an issue detected, or on a failure and pause change it to red.

Just a thought if it's possible it'd be pretty neat.

**Comment by QuinnDamerell** [comment]
Hey, @spitfire1337! Sorry for the delay. That does sound cool! It would be possible because the OctoEverywhere notification system supports WebHook callbacks! So it would be possible if you scripted up some logic to control the lights and hooked it up to the webhooks!

If you hook it up, send a video to our Discord, I would love to see it!
