### ISSUE TITLE
Klipper Mainsail - Multiple Printer Setup "farm view" not working

### ISSUE THREAD

**Issue by Edigorin** [QuinnDamerell/OctoPrint-OctoEverywhere#44]
I tried to setup "farm view" as described here: https://docs.mainsail.xyz/overview/settings/printers, but it's not working.

I tried using the default IP adress of Mainsail, as well as the shared connection adress with no luck.
I don't know if i'm using the wrong IP adress, or if the IP adress is blocked by moonraker, or if this is not possible with Octoeverywhere

**Comment by QuinnDamerell** [comment]
Thanks for the issue! This is by design for now. Each OctoEverywhere instance is tied to a moonraker instance, so there's a 1 to 1 relationship for notifications, failure detection, and such. You can run as many OctoEverywhere + Moonraker pairs as you want on one or multiple devices, but they can't share among each other right now.

Let me know if you have any other questions!
