### ISSUE TITLE
we can't talk until tomorrow?

### ISSUE THREAD

**Issue by working-name** [QuinnDamerell/OctoPrint-OctoEverywhere#46]
Hi there,

Just for my own understanding - "We Can't Talk Until Tomorrow 😭" refers to email notifications?

**Comment by QuinnDamerell** [comment]
Thanks for reaching out to ask! Since each notification type costs us funds to send, we must limit them for free accounts. We try to set the limit as high as possible, and it's at a reasonable level where more casual printers won't hit it. But if you do, the notifications are limited per notification platform per day.

Let me know if you have any other questions!
