### ISSUE TITLE
[Feature request] Set a delay for print complete webcam snapshot

### ISSUE THREAD

**Issue by ruddy17** [QuinnDamerell/OctoPrint-OctoEverywhere#65]
Currently on most of my 'print complete' notification snapshots the toolhead obstructs the view. It is kinda annoying and if the part is small, then I can't see it at all. I have a post-print macro to move the toolhead out of the way, however, the snapshot is made earlier than that. I suspect, that the screenshot considers the print done when all gcodes are put to the queue, but not when they are actually performed. So, I would suggest to either wait for the queue to empty, or just add a small delay of a few seconds for the snapshot. Maybe even add a macro for the snapshot, to be able to precisely control the moment it's done, for example to allow setting the lights for the best shot? 

Here is an example of current behavior:
![image](https://github.com/QuinnDamerell/OctoPrint-OctoEverywhere/assets/4340532/b3be8639-d7f6-4a46-a6dc-3ad283ef1a5f)

**Comment by QuinnDamerell** [comment]
Hey! Thanks for the feedback! I have worked on this system quite a lot, trying to get the most ideal final image, but it's a hard problem! The issue is printers are so dynamic that it's hard to know when you can get a nice clean shot with the print head out of the way. But using a custom macro or gcode command is a cool idea, I will look into that!
